from langchain_groq import ChatGroq
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableSequence, RunnableParallel ,RunnablePassthrough

load_dotenv(override=True)

#model initialization
model=ChatGroq(model="llama-3.1-8b-instant")
#_______________________# Define Prompts

prompt1 = PromptTemplate(
    template='write a joke about {topic}',
    input_variables=['topic']

)
#_______________________# Define Output Parser
parser = StrOutputParser()

prompt2 = PromptTemplate(
    template = 'Explain about the joke: {joke}',
    input_variables=['joke']
)

# Here we create a RunnableSequence that consists of the first prompt, the model, the parser, the second prompt, the model again, and the parser again. The output of each step is passed as input to the next step in the sequence.
joke_gen_chain = RunnableSequence(prompt1,model,parser)

# Here we create a RunnableParallel that consists of a RunnablePassthrough to pass the joke generated by the joke_gen_chain to the explanation chain, and a RunnableSequence that consists of the second prompt, the model, and the parser to generate an explanation for the joke.
parallel_chain = RunnableParallel({
    "joke": RunnablePassthrough(),
    "explanation": RunnableSequence(prompt2, model, parser)
})
# Finally, we create a final RunnableSequence that consists of the joke_gen_chain followed by the parallel_chain. This allows us to generate a joke and its explanation in one go.
final_chain = RunnableSequence(joke_gen_chain, parallel_chain)

result = final_chain.invoke({'topic':'Cricket'})
print(result)